import { TabWidget } from "std-widgets.slint";
import { SideBar } from "side_bar.slint";
import { ArchLinux, Debian, Settings } from "pages/pages.slint";


export component AppWindow inherits Window {
    icon: @image-url("../ui/assets/icons8-linux-48.png");
    preferred-width: 1100px;
    preferred-height: 600px;
    min-height: 500px;
    min-width: 700px;
    title: @tr("linpull");
    HorizontalLayout {
        side-bar := SideBar {
            title: @tr("Options");
            model: [@tr("Menu" => "Arch"), @tr("Menu" => "Debian"), @tr("Menu" => "Settings")];
        }

        if(side-bar.current-item == 0):  ArchLinux { }
        if(side-bar.current-item == 1):  Debian { }
        if(side-bar.current-item == 2): Settings { }
    }
}
