import { HorizontalBox, ProgressIndicator } from "std-widgets.slint";
export component DownloadStatus inherits HorizontalLayout {
    visible: false;
    in-out property <string> flavor;
    HorizontalBox {
        Rectangle {
            pg := ProgressIndicator {
                width: 300px;
                height: 10px;
                // progress: 20%;
                indeterminate: true;
            }
        }

        Text {
            text: pg.progress * 100 + "%";
            horizontal-alignment: left;
            vertical-alignment: center;
            font-weight: 600;
        }

        // Text {
        //     horizontal-alignment: left;
        //     vertical-alignment: center;
        //     text: "Downloading " + flavor;
        //     font-weight: 600;
        // }
    }
}
