import { HorizontalBox, ProgressIndicator } from "std-widgets.slint";
export component DownloadStatus inherits HorizontalLayout {
    visible: false;
    in-out property <string> flavor;
    flavor: "None";
    HorizontalBox {
        Text {
            vertical-alignment: center;
            text: "Downloading " + flavor;
            font-weight: 600;
        }

        Rectangle {
            ProgressIndicator {
                width: 250px;
                height: 20px;
                // progress: 20%;
                indeterminate: true;
            }
        }
    }
}
